Rename --profile to --plugins-profile
Locust 2.35.0 introduced --profile, which conflicts with locust-plugins's
pre-existing --profile. With locust 2.35.0 and locust-plugins 4.6.0 installed,
running locust fails with

argparse.ArgumentError: argument --profile: conflicting option string: --profile

This commit resolves the conflict by renaming --profile to --plugins-profile.